###############################################################################################################################
sekiro = Game.create(title: "Sekiro: Shadows Die Twice", image: "https://www.sekirothegame.com/content/dam/atvi/sekiro/gallery/Sekiro_24.jpg", number_of_players: "Singleplayer", description: "Save the prince", creator: "From Software", platform: "PS4", genre: "Soulsborne", site: "https://www.sekirothegame.com/", release_date: "March 22, 2019")

Review.create(rating: 5, comment: "An incredible action game immersed in mysterious stories and epic tales. Combat is fast paced and utterly brutal with the utmost importance of strategy and timing. Sekiro: Shadows Die Twice is the game of the year for 2019.", game: sekiro)
Review.create(rating: 2, comment: "This game is too hard and I don't understand the story at all. I hope people learn how to tell a coherent story that has a beginning, middle, and end. Also, combat could be more engaging but it is ok I guess.", game: sekiro)
###############################################################################################################################

###############################################################################################################################
naruto = Game.create(title: "Naruto: Clash of Ninja", image: "https://scontent.fnyc1-1.fna.fbcdn.net/v/t31.0-8/18156212_845355182272525_6578008672988182820_o.jpg?_nc_cat=100&_nc_sid=2d5d41&_nc_ohc=uQjoy7gCxZMAX8-aiNR&_nc_ht=scontent.fnyc1-1.fna&oh=e20236c2ce64c337580d87cdb2b72256&oe=5EC8F73D", number_of_players: "Singleplayer, Multiplayer", description: "Fight ninjas", creator: "Eighting", platform: "Gamecube, Wii", genre: "Fighting", site: "naruto.com", release_date: "April 11, 2003")

Review.create(rating: 3, comment: "A fun but minimal fighting game perfect for Naruto fans. It will always have a special place in my heart for its fantastic retelling of the beginning of the Naruto animated series. Combat is fun and the combos are true to the series. However, there is not a lot of characters to play as. Naruto: Clash of Ninja is a good game overall.", game: naruto)
Review.create(rating: 3, comment: "Seriously I don't know what the game designers were thinking the game tells u nothing about how to move around I still can't run in the battles and evidently according to the combo move list it's suppose to be possible? y the game no tell me how. the graphics are cool and the story mode is rather short yet pretty close to the anime storyline. the unlockable gallery is a neat bonus to make worth replaying stuff", game: naruto)
###############################################################################################################################

###############################################################################################################################
nmh = Game.create(title: "No More Heroes 2: Desperate Struggle", image: "https://i0.wp.com/www.blackshipbooks.com/wp-content/uploads/2014/03/nmh21a.jpg?fit=980%2C500", number_of_players: "Singleplayer", description: "Get your revenge", creator: "Grasshopper Manufacture", platform: "Wii", genre: "Action", site: "https://www.grasshopper.co.jp/en/projects/nomoreheroes2.html", release_date: "January 26, 2010")

Review.create(rating: 5, comment: "A brilliantly twisted love letter to the videogame medium, scrawled in blood and pixels.", game: nmh)
Review.create(rating: 5, comment: "A tale of revenge blood spattered with exciting bosses and fluid, powerful combat.", game: nmh)
###############################################################################################################################

###############################################################################################################################
portal = Game.create(title: "Portal 2", image: "https://www.wired.com/images_blogs/gamelife/2011/04/old_testchamber.jpg", number_of_players: "Singleplayer, Co - op", description: "Escape from the rogue AI", creator: "Valve", platform: "PC", genre: "Puzzle", site: "http://www.thinkwithportals.com/", release_date: "April 18, 2011")

Review.create(rating: 3, comment: "I may be the dumbest genius ever. At least, that's how I feel after playing Portal 2's fantastic single-player campaign. Many puzzles in the last third of the eight to 10 hours (perhaps less, depending on how clever you are) of its brain-bending puzzle “test chambers” had me convinced at one point or another that they were completely unsolvable, and that some bug or sadist game designer placed the exit just out of reach. I'd let out exasperated sighs as every attempt met with a dead end. I'd grimace in disapproval as I plummeted to my death for the tenth time. I'd consider surrender. Then, through either sudden revelation, divine inspiration, or total accident, it would come to me: use the orange Propulsion Gel to reach the energy bridge, then catapult across the chasm and shift my blue portal to the inclined surface (in mid-air, mind you) to launch me up to the ledge, grab the refraction cube and redirect the laser beam to wipe out the turrets and activate the switch! It's so simple, I can't believe I didn't see it until now. One half of Portal 2's brilliance is making me kick myself for not thinking of the impossible; the other is making me feel immensely satisfied with myself when I finally do, again and again.", game: portal)
Review.create(rating: 3, comment: "Portal 2 draws from the award-winning formula of innovative gameplay, story, and music that earned the original Portal over 70 industry accolades and created a cult following. The single-player portion of Portal 2 introduces a cast of dynamic new characters, a host of fresh puzzle elements, and a much larger set of devious test chambers", game: portal)
###############################################################################################################################

###############################################################################################################################
zelda = Game.create(title: "The Legend of Zelda: Breath of the Wild", image: "https://img-eshop.cdn.nintendo.net/i/7c8f2e897c9e025649f97d4c9d5e1f92497bd6217bd442d6de8de17c46142e78.jpg?w=1000", number_of_players: "Singleplayer", description: "Save the princess", creator: "Nintendo", platform: "Switch", genre: "Adventure RPG", site: "https://www.zelda.com/breath-of-the-wild/", release_date: "March 3, 2017")

Review.create(rating: 5, comment: "Breath of the Wild is Nintendo's most impressive and ambitious game to date", game: zelda)
Review.create(rating: 5, comment: "I... have never been so taken aback by the vastness of a game. You really don't need to read another review, Zelda alone is worth the price of a switch. Like if they sold this game for 300 dollars I would probably buy it. In fact, it's the only Switch game I own, and have no real plans to purchase anything else because between the original game and Master Mode, I will be getting a divorce soon so I can spend more time collecting mushrooms and climbing mountains.", game: zelda)
###############################################################################################################################
