# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Game.create(title: "Sekiro: Shadows Die Twice", image: "https://www.sekirothegame.com/content/dam/atvi/sekiro/gallery/Sekiro_24.jpg", number_of_players: "Singleplayer", description: "Save the prince", creator: "From Software", platform: "PS4", genre: "Soulsborne", site: "https://www.sekirothegame.com/", release_date: "March 22, 2019")
Game.create(title: "Naruto: Clash of Ninja", image: "https://scontent.fnyc1-1.fna.fbcdn.net/v/t31.0-8/18156212_845355182272525_6578008672988182820_o.jpg?_nc_cat=100&_nc_sid=2d5d41&_nc_ohc=uQjoy7gCxZMAX8-aiNR&_nc_ht=scontent.fnyc1-1.fna&oh=e20236c2ce64c337580d87cdb2b72256&oe=5EC8F73D", number_of_players: "Singleplayer, Multiplayer", description: "Fight ninjas", creator: "Eighting", platform: "Gamecube, Wii", genre: "Fighting", site: "naruto.com", release_date: "April 11, 2003")
Game.create(title: "No More Heroes 2: Desperate Struggle", image: "https://i0.wp.com/www.blackshipbooks.com/wp-content/uploads/2014/03/nmh21a.jpg?fit=980%2C500", number_of_players: "Singleplayer", description: "Get your revenge", creator: "Grasshopper Manufacture", platform: "Wii", genre: "Action", site: "https://www.grasshopper.co.jp/en/projects/nomoreheroes2.html", release_date: "January 26, 2010")
Game.create(title: "Portal 2", image: "https://www.wired.com/images_blogs/gamelife/2011/04/old_testchamber.jpg", number_of_players: "Singleplayer, Co - op", description: "Escape from the rogue AI", creator: "Valve", platform: "PC", genre: "Puzzle", site: "http://www.thinkwithportals.com/", release_date: "April 18, 2011")
Game.create(title: "The Legend of Zelda: Breath of the Wild", image: "https://img-eshop.cdn.nintendo.net/i/7c8f2e897c9e025649f97d4c9d5e1f92497bd6217bd442d6de8de17c46142e78.jpg?w=1000", number_of_players: "Singleplayer", description: "Save the princess", creator: "Nintendo", platform: "Switch", genre: "Adventure RPG", site: "https://www.zelda.com/breath-of-the-wild/", release_date: "March 3, 2017")
Game.create(title: "Minecraft", image: "//upload.wikimedia.org/wikipedia/en/thumb/5/51/Minecraft_cover.png/220px-Minecraft_cover.png", number_of_players: "Singleplayer, Multiplayer", description: "Building game", creator: "Mojang", platform: "All", genre: "Sandbox/Survival", site: "https://www.playstation.com/en-us/games/minecraft-ps4/", release_date: "11/18/2011")
Game.create(title: "Tetris", image: "https://romsforever.co/wp-content/uploads/2019/09/Tetris_box__09828.1398275979.jpg", number_of_players: "Singleplayer", description: "Fit the falling blocks together to advance", creator: "Alexey Pajitnov", platform: "Nintendo", genre: "puzzle", site: "https://tetris.com/", release_date: "6/6/1984")
Game.create(title: "World of Warcraft", image: "//upload.wikimedia.org/wikipedia/en/thumb/9/91/WoW_Box_Art1.jpg/220px-WoW_Box_Art1.jpg", number_of_players: "Online Multiplayer", description: "Team up with your friends and complete quests to level up your character", creator: "Blizzard", platform: "PC", genre: "MMO RPG", site: "https://worldofwarcraft.com/en-us/", release_date: "11/23/2004")
Game.create(title: "Fortnite", image: "https://i.insider.com/5c366de02a5b7442d75cda92?width=1300&format=jpeg&auto=webp", number_of_players: "Online Multiplayer", description: "", creator: "Epic Games", platform: "PC, XBox, PS4, Mac, Mobile, Nintendo", genre: "Battle Royale", site: "https://www.epicgames.com/fortnite/en-US/home", release_date: "7/21/2017")
